name: Rust

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:

    runs-on: ubicloud-standard-2
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
        add-job-id-key: "false"
    - name: Build
      run: cargo build --workspace --all-targets --all-features --verbose
    - name: Run tests
      run: cargo test --workspace --all-targets --all-features --verbose


  clippy_check:

    runs-on: ubicloud-standard-2
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          add-job-id-key: "false"
      - name: Clippy (deny warnings)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
